```{r}
# Load necessary libraries
library(Seurat)               
library(scCustomize)          
library(biomaRt)
library(dplyr)
library(knitr)
library(roxygen2)
library(ggplot2)
library(SeuratData)
library(SeuratDisk)

# Set seed for reproducibility
set.seed(1234)

# Increase memory usage
options(future.globals.maxSize=20000*1024^2)  # allocates approximately 20GiB for global variables in future expressions
```

```{r}
# List of CRAN packages
cran_packages <- c(
  "Seurat",       # Core package for scRNA-seq analysis
  "scCustomize",  # Enhances customization of Seurat workflows
  "SoupX",        # Removes ambient RNA contamination
  "biomaRt",      # Access BioMart and Ensembl databases
  "dplyr",        # Data manipulation
  "knitr",        # Report generation
  "roxygen2"      # Documentation
)

# Install missing CRAN packages
installed_cran <- cran_packages %in% installed.packages()
if (any(!installed_cran)) {
  install.packages(cran_packages[!installed_cran])
}

# Load CRAN packages
lapply(cran_packages, library, character.only = TRUE)

# Install and load DoubletFinder from GitHub
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
if (!"DoubletFinder" %in% installed.packages()) {
  remotes::install_github("chris-mcginnis-ucsf/DoubletFinder")
}
library(DoubletFinder)

# Set seed for reproducibility
set.seed(1234)

# Increase memory usage
options(future.globals.maxSize=20000*1024^2)  # allocates approximately 20GiB for global variables in future expressions
```

```{r}
mouse_neurons <- readRDS("data/origin_data/mouse_neurons.rds")
mouse_neurons_skinnider <- readRDS("data/origin_data/mouse_neurons_skinnider.rds")
```

```{r}	
neurons_mouse_counts <- GetAssayData(mouse_neurons, layer = "counts")
neurons_mouse_skinnider_counts <- GetAssayData(mouse_neurons_skinnider, layer = "counts")
```


```{r}
# Merge mouse and human datasets
mouse_neurons = CreateSeuratObject(counts = neurons_mouse_counts)
mouse_neurons$species <- "mouse"
mouse_neurons_skinnider <- CreateSeuratObject(counts = neurons_mouse_skinnider_counts)
mouse_neurons_skinnider$species <- "mouse"
```

```{r}	
# Drop all layers from other papers
mouse_neurons <- subset(x = mouse_neurons, subset = orig.ident %in% c("MATSON", "KATHE", "KNAF3", "KNAF4", "BOUV5"))
# mouse_neurons <- subset(x = mouse_neurons, subset = orig.ident %in% c("KNAF11", "KNAF10", "KNAF9", "KNAF8", "BOUV6", "BOUV7"))
```
```{r}
merged_neurons <- merge(mouse_neurons, mouse_neurons_skinnider)
```

```{r}
mouse_neurons <- merged_neurons
```

```{r}
mouse_neurons[['RNA']] <- JoinLayers(object = mouse_neurons[['RNA']])
```

```{r}
mouse_neurons <- split(mouse_neurons, f = mouse_neurons$orig.ident)
```

```{r}
mouse_neurons <- NormalizeData(mouse_neurons)
mouse_neurons <- FindVariableFeatures(mouse_neurons)
mouse_neurons <- ScaleData(mouse_neurons)
mouse_neurons <- RunPCA(mouse_neurons)
```


```{r}
mouse_neurons <- IntegrateLayers(object = mouse_neurons, method = 'RPCAIntegration', orig.reduction = 'pca', new.reduction = 'rpca', reference = 5, verbose = TRUE)
```

```{r}
mouse_neurons <- FindNeighbors(mouse_neurons, reduction = 'rpca', dims = 1:30)
mouse_neurons <- FindClusters(mouse_neurons, resolution = 2, cluster_names = 'rpca_clusters')

# Plot the integrated UMAP
mouse_neurons <- RunUMAP(mouse_neurons, reduction = 'rpca', dims = 1:30, reduction.name = 'umap.rpca')
```

```{r}  
DimPlot(mouse_neurons, reduction = 'umap.rpca',group.by = "orig.ident")
```


```{r}	
# Join layers
mouse_neurons <- JoinLayers(object = mouse_neurons)
```

```{r}
## Downgrade to not v5 object to solve SaveH5Seurat error
mouse_neurons[["RNA3"]] <- as(object = mouse_neurons[["RNA"]], Class = "Assay")
DefaultAssay(mouse_neurons) <- "RNA3"
mouse_neurons[["RNA"]] <- NULL
mouse_neurons[["RNA"]] <- mouse_neurons[["RNA3"]]
DefaultAssay(mouse_neurons) <- "RNA"
mouse_neurons[["RNA3"]] <- NULL
```

```{r}
# Add annotation of V1 neurons
mouse_neurons$training_labels <- -1
mouse_neurons$training_labels[mouse_neurons$orig.ident == "KNAF4"] <- 1
mouse_neurons$training_labels[mouse_neurons$orig.ident == "KNAF3"] <- 0
```

```{r}
# Add annotation of V1 neurons
mouse_neurons$citeseq <- NaN
mouse_neurons$citeseq[mouse_neurons$orig.ident == "KNAF3"] <- 'CiteSeq-'
mouse_neurons$citeseq[mouse_neurons$orig.ident == "KNAF4"] <- 'CiteSeq+'
```

```{r}  
DimPlot(mouse_neurons, reduction = 'umap.rpca',group.by = "citeseq")
```

```{r}
# Save the integrated dataset as h5
SaveH5Seurat(mouse_neurons, filename = "mouse_neurons+skinnider.h5Seurat", overwrite = TRUE)

```	

```{r}
Convert(source = "mouse_neurons+skinnider.h5Seurat", dest = "mouse_neurons+skinnider.h5ad", overwrite = TRUE)
```	

```{r}
# Count the number of cells of each origin
table(mouse_neurons$orig.ident)
```